name: On Commit to Main

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    uses: andrew-codes/forecast-work/.github/workflows/lint-and-test.yml@main
  
  build:
    needs: [lint_and_test]
    uses: andrew-codes/forecast-work/.github/workflows/build.yml@main
    with:
      publish_flag: "--publish always"
 
  e2e:
    needs: [build]
    uses: andrew-codes/forecast-work/.github/workflows/e2e-test.yml@main

  package_and_publish:
    needs: [lint_and_test, build, e2e]
    uses: andrew-codes/forecast-work/.github/workflows/package.yml@main
    with:
      publish_flag: "--publish always"