name: Create Development Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test/ci
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  package_windows:
    name: Package application (Windows)
    runs-on: windows-latest
    needs:
      - lint_and_test
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn add electron-builder
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Package and publish application
        run: yarn release/windows
        env:
          GITHUB_TOKEN: ${{ github.token }}

  package_linux:
    name: Package application (Linux)
    runs-on: ubuntu-latest
    needs:
    - lint_and_test
    - build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn add electron-builder
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Package and publish application
        run: yarn release/linux
        env:
          GITHUB_TOKEN: ${{ github.token }}

  package_osx:
    name: Package application (OSX)
    runs-on: macos-latest
    needs:
    - lint_and_test
    - build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn add electron-builder dmg-license
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Package and publish application
        run: yarn release/osx
        env:
          GITHUB_TOKEN: ${{ github.token }}
