name: On Commit to Main

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    uses: andrew-codes/forecast-work/.github/workflows/lint-and-test.yml@main
  
  build:
    uses: andrew-codes/forecast-work/.github/workflows/build-and-package-apps.yml@main
    with:
      publish_flag: "--publish always"