name: Test and publish apps for release

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    uses: andrew-codes/forecast-work/.github/workflows/lint-and-test.yml@main
  
  build:
    uses: andrew-codes/forecast-work/.github/workflows/build-and-package-apps.yml@main

  publish:
    uses: andrew-codes/forecast-work/.github/workflows/publish-apps.yml@main