name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for test and packaging to succeeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: Package for Release
          repo-token: ${{ github.token }}
          wait-interval: 4
      - name: Checkout for changelog generation
        uses: actions/checkout@v2
      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@master
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download artifacts from packaging workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: on-commit-to-main.yml
          workflow_conclusion: success
          commit: ${{ github.ref }}
          branch: main
          path: dist
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Agile Forecasting.exe
          asset_name: Agile_Forecasting_for_Windows.exe
          asset_content_type: application/octet-stream
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Agile Forecasting
          asset_name: Agile_Forecasting_for_Linux
          asset_content_type: application/octet-stream.
