name: Package for Release

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  package_exec_for_windows:
    runs-on: windows-2022
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Create Executable
        run: |
          pyinstaller --clean --distpath="dist" --name="Agile Forecasting.exe" --onefile ./src/app.py
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: Release Candidate Executable for Windows
          path: "dist/Agile Forecasting.exe"

  package_exec_for_linux:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Create Executable
        run: |
          pyinstaller \
            --add-data="README.md:." \
            --clean \
            --distpath="dist" \
            --name="Agile Forecasting" \
            --onefile \
            ./src/app.py
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: Release Candidate Executable for Linux
          path: "dist/Agile Forecasting"
