name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  change_log:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install changelog generator
        run: |
          gem install github_changelog_generator
      - name: Checkout for changelog generation
        uses: actions/checkout@v2
      - name: Generate changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ github.token }}
        run: |
          IFS='/' read -ra REPO_PARTS <<< "$GITHUB_REPOSITORY"
          github_changelog_generator -u ${REPO_PARTS[0]} -p ${REPO_PARTS[1]}
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG
          path: CHANGELOG.md

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [change_log]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: dist/CHANGELOG/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}