name: Test and publish apps for PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    uses: andrew-codes/forecast-work/.github/workflows/lint-and-test.yml@main
  
  build:
    uses: andrew-codes/forecast-work/.github/workflows/build-and-package-apps.yml@main
